Add a section for the background blur field in VideoFrameMetadata
w3c/mediacapture-extensions pull request #159
Opened 2024-11-12 20:03 UTC by markafoltz

See https://github.com/markafoltz/camera-effects for more details.

2024-11-12 20:11 UTC, markafoltz reviewed
Overall looks good, a couple of feedbacks on the IDL.

2024-11-12 20:11 UTC, markafoltz commented on index.html
> +    <h2>Camera Effect Status</h2>
```suggestion
    <h2>Background Blur Effect Status</h2>
```

2024-11-12 20:11 UTC, markafoltz commented on index.html
> +    <h2>Camera Effect Status</h2>
The current proposal is scoped to blur, we can generalize later as additional effects are considered.

2024-11-12 20:11 UTC, markafoltz commented on index.html
> +    <p>The {{VideoFrameMetadata}} interface exposes the effect state as a property,
```suggestion
    <p>The {{VideoFrameMetadata}} interface exposes the blur state as a property,
```

2024-11-12 20:11 UTC, markafoltz commented on index.html
> +            <p>The state of the background blur effect for the current frame.</p>
Should explain what it means for the property to be present or missing.

2024-11-12 20:11 UTC, markafoltz commented on index.html
> +  boolean enabled;
I think this should be a required property.  If `background_blur` is present, `enabled` should have a value.

2024-11-22 22:40 UTC, aboba requested changes
Other than the MSTG/VTG issue, looks ok.

2024-11-29 18:32 UTC, eladalon1983 commented on index.html
> +// main.js:
Is this contrasted with code in another .js file or elsewhere?

2025-02-05 18:47 UTC, jan-ivar requested changes

2025-02-05 18:47 UTC, jan-ivar commented on index.html
> +      scenarios where the app must ensure user privacy by never sending an
Let's avoid normative "must". I also don't think we want to overstate the security properties of camera blurring. OS implementations might differ significantly, and they don't necessarily pass everyone's definition of a security measure.

```suggestion
      which allows apps to know the state for every frame. This can be helpful for
      scenarios where the app wishes to help protect user privacy by never sending an
```

2025-02-05 18:47 UTC, jan-ivar commented on index.html
> +      un-blurred frame off of the user's device.</p>
Mediacapture uses "device" to mean cameras and mics. Maybe:
```suggestion
      un-blurred frame off of the user's system.</p>
```

2025-02-13 15:58 UTC, jan-ivar approved these changes
LGTM once the example is fixed to spec.

2025-02-13 15:58 UTC, jan-ivar commented on index.html
> +const trackGenerator = new VideoTrackGenerator({ kind: "video" });
These APIs are worker-only in the spec, whereas this example is still main thread.

You need to add a worker. See https://blog.mozilla.org/webrtc/unbundling-mediastreamtrackprocessor-and-videotrackgenerator/ for some examples.

2025-02-19 09:39 UTC, guidou approved these changes

2025-02-19 09:40 UTC, merged